application: zorcraft-game
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: rocket_engine.wsgi
  login: required

libraries:
- name: django
  version: 1.3

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'